Tests for create files and folders + setup
The tests required some refactoring in order for them to work. This has made a breaking change when calling from the command line which I will look into another time:

python dsutils/setup.py
Traceback (most recent call last):
  File "dsutils\setup.py", line 1, in <module>
    from .internals import *
ImportError: attempted relative import with no known parent package